# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\AboutDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper
from utils.ImgHelper import ImgHelper

from icon.svg import close, logoIcon
from img.png import logo


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.setWindowFlags(Qt.CustomizeWindowHint)
        AboutDialog.resize(600, 400)
        AboutDialog.setAutoFillBackground(False)
        AboutDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(AboutDialog)
        QMetaObject.connectSlotsByName(AboutDialog)

        self.setupMainLayout(AboutDialog)
        self.setupDialogNav()
        self.setupContent()

    def retranslateUi(self, AboutDialog):
        _translate = QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "關於系統"))
        AboutDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, AboutDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        AboutDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupContent(self):

        logos = QLabel()
        logos.setPixmap(QPixmap.fromImage(ImgHelper.getImageQtfromBytes(logo)))
        logos.setAlignment(Qt.AlignCenter)
        logos.setScaledContents(True)
        logos.setFixedSize(185.04, 108.26)

        copyright = QLabel()
        copyright.setText("Copyright © 2020 CHANG CHIH HSIANG All rights reserved.\n授權淡江大學資訊處使用")
        copyright.setFont(QFont("Noto Sans TC Regular", 10))
        copyright.setStyleSheet("QLabel{color: #232323;}")
        copyright.setAlignment(Qt.AlignCenter)

        self.mainLayout.addWidget(logos, alignment=Qt.AlignTop|Qt.AlignHCenter)
        self.mainLayout.addWidget(copyright, alignment=Qt.AlignTop|Qt.AlignHCenter)






