# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\AuthDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon



class Ui_CheckAuthDialog(object):
    def setupUi(self, CheckAuthDialog):
        CheckAuthDialog.setObjectName("CheckAuthDialog")
        CheckAuthDialog.resize(400, 150)
        CheckAuthDialog.setWindowFlags(Qt.CustomizeWindowHint)
        CheckAuthDialog.setAutoFillBackground(False)
        CheckAuthDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(CheckAuthDialog)
        QMetaObject.connectSlotsByName(CheckAuthDialog)

        self.setupMainLayout(CheckAuthDialog)
        self.setupDialogNav()
        self.setupFormArea()
        self.setupNavArea()

    def retranslateUi(self, CheckAuthDialog):
        _translate = QCoreApplication.translate
        CheckAuthDialog.setWindowTitle(_translate("CheckAuthDialog", "管理員驗證"))
        CheckAuthDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, CheckAuthDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        CheckAuthDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupFormArea(self):

        formArea = QWidget()
        formAreaLayout = QFormLayout()

        stuNumLabel = QLabel()
        stuNumLabel.setText("請輸入操作人員學號：")
        stuNumLabel.setFont(QFont("Noto Sans TC Regular", 10))
        stuNumLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.stuNumLineEdit = QLineEdit()
        self.stuNumLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.stuNumLineEdit.setAlignment(Qt.AlignCenter)
        self.stuNumLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.stuNumLineEdit.setStyleSheet("QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")
        self.stuNumLineEdit.setEchoMode(QLineEdit.PasswordEchoOnEdit)


        formAreaLayout.addRow(stuNumLabel, self.stuNumLineEdit)
        formAreaLayout.setContentsMargins(30, 0, 30, 0)
        formArea.setLayout(formAreaLayout)

        self.mainLayout.addWidget(formArea, alignment=Qt.AlignVCenter)


    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()


        self.comfirm = QPushButton()
        self.comfirm.setText("送出")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)
