# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\ChgAuthDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon


class Ui_ChgAuthDialog(object):
    def setupUi(self, ChgAuthDialog):
        ChgAuthDialog.setObjectName("ChgAuthDialog")
        ChgAuthDialog.setWindowFlags(Qt.CustomizeWindowHint)
        ChgAuthDialog.resize(400, 150)
        ChgAuthDialog.setAutoFillBackground(True)
        ChgAuthDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(ChgAuthDialog)
        QMetaObject.connectSlotsByName(ChgAuthDialog)

        self.setupMainLayout(ChgAuthDialog)
        self.setupDialogNav()
        self.setupFormArea()
        self.setupNavArea()

    def retranslateUi(self, ChgAuthDialog):
        _translate = QCoreApplication.translate
        ChgAuthDialog.setWindowTitle(_translate("ChgAuthDialog", "系統密碼變更"))
        ChgAuthDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, ChgAuthDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        ChgAuthDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupFormArea(self):

        formArea = QWidget()
        formAreaLayout = QFormLayout()

        passwordLabel = QLabel()
        passwordLabel.setText("請輸入新管理員密碼：")
        passwordLabel.setAlignment(Qt.AlignLeft)
        passwordLabel.setFont(QFont("Noto Sans TC Regular", 10))
        passwordLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.passwordLineEdit = QLineEdit()
        self.passwordLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.passwordLineEdit.setAlignment(Qt.AlignCenter)
        self.passwordLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.passwordLineEdit.setStyleSheet("QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")
        self.passwordLineEdit.setEchoMode(QLineEdit.Password)

        checkPasswordLabel = QLabel()
        checkPasswordLabel.setText("請再次輸入新管理員密碼：")
        checkPasswordLabel.setAlignment(Qt.AlignLeft)
        checkPasswordLabel.setFont(QFont("Noto Sans TC Regular", 10))
        checkPasswordLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.checkPasswordLineEdit = QLineEdit()
        self.checkPasswordLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.checkPasswordLineEdit.setAlignment(Qt.AlignCenter)
        self.checkPasswordLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.checkPasswordLineEdit.setStyleSheet(
            "QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")
        self.checkPasswordLineEdit.setEchoMode(QLineEdit.Password)


        formAreaLayout.addRow(passwordLabel, self.passwordLineEdit)
        formAreaLayout.addRow(checkPasswordLabel, self.checkPasswordLineEdit)
        formAreaLayout.setContentsMargins(30, 0, 30, 0)
        formArea.setLayout(formAreaLayout)

        self.mainLayout.addWidget(formArea, alignment=Qt.AlignVCenter)


    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()


        self.comfirm = QPushButton()
        self.comfirm.setText("送出")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)
