# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\EditScheduleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon


class Ui_EditScheduleDialog(object):
    def setupUi(self, EditScheduleDialog):
        EditScheduleDialog.setObjectName("EditScheduleDialog")
        EditScheduleDialog.setWindowFlags(Qt.CustomizeWindowHint)
        EditScheduleDialog.resize(1000, 450)
        EditScheduleDialog.setAutoFillBackground(False)
        EditScheduleDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(EditScheduleDialog)
        QMetaObject.connectSlotsByName(EditScheduleDialog)

        self.setupMainLayout(EditScheduleDialog)
        self.setupDialogNav()
        self.setupCenterialArea()
        self.setupContentArea()
        self.setupNavArea()

    def retranslateUi(self, EditScheduleDialog):
        _translate = QCoreApplication.translate
        EditScheduleDialog.setWindowTitle(_translate("EditScheduleDialog", "考勤記錄編輯"))
        EditScheduleDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, EditScheduleDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        EditScheduleDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupCenterialArea(self):
        centerialArea = QWidget()
        self.centerialAreaLayout = QHBoxLayout()
        centerialArea.setLayout(self.centerialAreaLayout)

        self.mainLayout.addWidget(centerialArea)

    def setupContentArea(self):
        contentArea = QWidget()
        contentAreaLayout = QVBoxLayout()



        dateArea = QWidget()
        dateAreaLayout = QHBoxLayout()

        dateStartLabel = QLabel()
        dateStartLabel.setText("時期起始：")
        dateStartLabel.setFont(QFont("Noto Sans TC Regular",10))
        dateStartLabel.setAlignment(Qt.AlignLeft)
        dateAreaLayout.addWidget(dateStartLabel, 1, alignment=Qt.AlignLeft)

        self.dateStart = QDateEdit()
        self.dateStart.setFont(QFont("Noto Sans TC Regular", 10))
        self.dateStart.setAlignment(Qt.AlignCenter)
        self.dateStart.setCursor(QCursor(Qt.IBeamCursor))
        self.dateStart.setDisplayFormat("yyyy-MM-dd")
        self.dateStart.setStyleSheet("QDateEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QDateEdite:selected{border-bottom:1px solid #f7931e;}")
        dateAreaLayout.addWidget(self.dateStart, 3)

        dateEndLabel = QLabel()
        dateEndLabel.setText("時期結束：")
        dateEndLabel.setFont(QFont("Noto Sans TC Regular", 10))
        dateEndLabel.setAlignment(Qt.AlignLeft)
        dateAreaLayout.addWidget(dateEndLabel, 1, alignment=Qt.AlignLeft)

        self.dateEnd = QDateEdit()
        self.dateEnd.setFont(QFont("Noto Sans TC Regular", 10))
        self.dateEnd.setAlignment(Qt.AlignCenter)
        self.dateEnd.setCursor(QCursor(Qt.IBeamCursor))
        self.dateEnd.setDisplayFormat("yyyy-MM-dd")
        self.dateEnd.setStyleSheet("QDateEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QDateEdite:selected{border-bottom:1px solid #f7931e;}")
        dateAreaLayout.addWidget(self.dateEnd, 3)

        dateArea.setLayout(dateAreaLayout)


        self.listArea = QTreeWidget()
        self.listArea.setFont(QFont("Noto Sans TC Regular", 10))
        self.listArea.setStyleSheet(
            "QHeaderView::section{color: #f7931e; border: 0; background-color: white;} QTreeWidget{border-style: none;} QTreeWidget::item:hover{background-color: #FFD4A2; color: black;} QTreeWidget::item:selected{background-color: #FCA642; color: white;}")
        self.listArea.setHeaderLabels(["工讀生編號", "工讀生姓名", "日期", "班別", "實習室", "簽到時間", "簽退時間", "簽到狀態"])
        self.listArea.header().setDefaultAlignment(Qt.AlignCenter)
        self.listArea.horizontalScrollBar().setStyleSheet(
            "QScrollBar:horizontal{ border-radius: 5px; background: white; padding-left:2px; padding-right: 2px;} QScrollBar::handle:horizontal{background: #9F9F9F; border-radius: 5px; margin-top: 3px; margin-bottom: 3px;} QScrollBar::handle:horizontal:hover{background: #3d3d3d; border-radius: 5px; margin-top: 3px; margin-bottom: 3px;} QScrollBar::add-line:horizontal{height: 0px; width: 0px; image: url('')} QScrollBar::sub-line:horizontal{height: 0px; width: 0px; image: url('')}")
        self.listArea.verticalScrollBar().setStyleSheet(
            "QScrollBar:vertical{ border-radius: 5px; background: white; padding-top:2px; padding-bottom: 2px;} QScrollBar::handle:vertical{background: #9F9F9F; border-radius: 5px; margin-left: 3px; margin-right: 3px;} QScrollBar::handle:vertical:hover{background: #3d3d3d; border-radius: 5px; margin-left: 3px; margin-right: 3px;} QScrollBar::add-line:horizontal{height: 0px; width: 0px; image: url('')} QScrollBar::sub-line:vertical{height: 0px; width: 0px; image: url('')}")

        contentAreaLayout.addWidget(dateArea, alignment=Qt.AlignTop)
        contentAreaLayout.addWidget(self.listArea)
        contentArea.setLayout(contentAreaLayout)

        self.centerialAreaLayout.addWidget(contentArea)

    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QVBoxLayout()

        self.query = QPushButton()
        self.query.setText("查詢資料")
        self.query.setFont(QFont("Noto Sans TC Regular", 10))
        self.query.setCursor(QCursor(Qt.PointingHandCursor))
        self.query.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.editOnTimeCheckIn = QPushButton()
        self.editOnTimeCheckIn.setText("簽到準時")
        self.editOnTimeCheckIn.setFont(QFont("Noto Sans TC Regular", 10))
        self.editOnTimeCheckIn.setCursor(QCursor(Qt.PointingHandCursor))
        self.editOnTimeCheckIn.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.editOnTimeCheckOut = QPushButton()
        self.editOnTimeCheckOut.setText("簽退準時")
        self.editOnTimeCheckOut.setFont(QFont("Noto Sans TC Regular", 10))
        self.editOnTimeCheckOut.setCursor(QCursor(Qt.PointingHandCursor))
        self.editOnTimeCheckOut.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.editLate = QPushButton()
        self.editLate.setText("簽到遲到")
        self.editLate.setFont(QFont("Noto Sans TC Regular", 10))
        self.editLate.setCursor(QCursor(Qt.PointingHandCursor))
        self.editLate.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.editExcused = QPushButton()
        self.editExcused.setText("簽退早退")
        self.editExcused.setFont(QFont("Noto Sans TC Regular", 10))
        self.editExcused.setCursor(QCursor(Qt.PointingHandCursor))
        self.editExcused.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.clearCheckIn = QPushButton()
        self.clearCheckIn.setText("清除簽到")
        self.clearCheckIn.setFont(QFont("Noto Sans TC Regular", 10))
        self.clearCheckIn.setCursor(QCursor(Qt.PointingHandCursor))
        self.clearCheckIn.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.clearCheckOut = QPushButton()
        self.clearCheckOut.setText("清除簽退")
        self.clearCheckOut.setFont(QFont("Noto Sans TC Regular", 10))
        self.clearCheckOut.setCursor(QCursor(Qt.PointingHandCursor))
        self.clearCheckOut.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("關閉視窗")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addWidget(self.query)
        navAreaLayout.addWidget(self.editOnTimeCheckIn)
        navAreaLayout.addWidget(self.editOnTimeCheckOut)
        navAreaLayout.addWidget(self.editLate)
        navAreaLayout.addWidget(self.editExcused)
        navAreaLayout.addWidget(self.clearCheckIn)
        navAreaLayout.addWidget(self.clearCheckOut)
        navAreaLayout.addWidget(self.cancel)
        navAreaLayout.addStretch()
        navArea.setLayout(navAreaLayout)

        self.centerialAreaLayout.addWidget(navArea, alignment=Qt.AlignRight)


    def loadingList(self, data: list):
        self.listArea.clear()

        for item in data:
            qTreeWidgetItem = QTreeWidgetItem(item[1:])
            qTreeWidgetItem.setData(0, Qt.UserRole, item[0])
            for i in range(0, qTreeWidgetItem.columnCount()):
                qTreeWidgetItem.setTextAlignment(i, Qt.AlignCenter)

            self.listArea.addTopLevelItem(qTreeWidgetItem)


