# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\EditVacationCellDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon


class Ui_EditVacationCellDialog(object):
    def setupUi(self, EditVacationCellDialog):
        EditVacationCellDialog.setObjectName("EditVacationCellDialog")
        EditVacationCellDialog.setWindowFlags(Qt.CustomizeWindowHint)
        EditVacationCellDialog.resize(450, 200)
        EditVacationCellDialog.setAutoFillBackground(True)
        EditVacationCellDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(EditVacationCellDialog)
        QMetaObject.connectSlotsByName(EditVacationCellDialog)

        self.setupMainLayout(EditVacationCellDialog)
        self.setupDialogNav()
        self.setupFormArea()
        self.setupNavArea()

    def retranslateUi(self, EditVacationCellDialog):
        _translate = QCoreApplication.translate
        EditVacationCellDialog.setWindowTitle(_translate("EditVacationCellDialog", "假日編修"))
        EditVacationCellDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, EditVacationCellDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        EditVacationCellDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupFormArea(self):

        formArea = QWidget()
        formAreaLayout = QFormLayout()

        nameLabel = QLabel()
        nameLabel.setText("請輸入假日名稱：")
        nameLabel.setAlignment(Qt.AlignLeft)
        nameLabel.setFont(QFont("Noto Sans TC Regular", 10))
        nameLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.nameLineEdit = QLineEdit()
        self.nameLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.nameLineEdit.setAlignment(Qt.AlignCenter)
        self.nameLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.nameLineEdit.setStyleSheet(
            "QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")

        dateStartLabel = QLabel()
        dateStartLabel.setText("請指定起始日期：")
        dateStartLabel.setAlignment(Qt.AlignLeft)
        dateStartLabel.setFont(QFont("Noto Sans TC Regular", 10))
        dateStartLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.dateStart = QDateEdit()
        self.dateStart.setFont(QFont("Noto Sans TC Regular", 10))
        self.dateStart.setAlignment(Qt.AlignCenter)
        self.dateStart.setCursor(QCursor(Qt.IBeamCursor))
        self.dateStart.setDisplayFormat("yyyy-MM-dd")
        self.dateStart.setStyleSheet(
            "QDateEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QDateEdite:selected{border-bottom:1px solid #f7931e;}")


        dateEndLabel = QLabel()
        dateEndLabel.setText("請指定結束日期：")
        dateEndLabel.setAlignment(Qt.AlignLeft)
        dateEndLabel.setFont(QFont("Noto Sans TC Regular", 10))
        dateEndLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.dateEnd = QDateEdit()
        self.dateEnd.setFont(QFont("Noto Sans TC Regular", 10))
        self.dateEnd.setAlignment(Qt.AlignCenter)
        self.dateEnd.setCursor(QCursor(Qt.IBeamCursor))
        self.dateEnd.setDisplayFormat("yyyy-MM-dd")
        self.dateEnd.setStyleSheet(
            "QDateEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QDateEdite:selected{border-bottom:1px solid #f7931e;}")




        formAreaLayout.addRow(nameLabel, self.nameLineEdit)
        formAreaLayout.addRow(dateStartLabel, self.dateStart)
        formAreaLayout.addRow(dateEndLabel, self.dateEnd)
        formAreaLayout.setContentsMargins(30, 0, 30, 0)
        formArea.setLayout(formAreaLayout)

        self.mainLayout.addWidget(formArea, alignment=Qt.AlignVCenter)


    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()


        self.comfirm = QPushButton()
        self.comfirm.setText("送出")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)
