# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\EditShiftCellDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon


class Ui_EditShiftCellDialog(object):
    def setupUi(self, EditShiftCellDialog):
        EditShiftCellDialog.setObjectName("EditShiftCellDialog")
        EditShiftCellDialog.setWindowFlags(Qt.CustomizeWindowHint)
        EditShiftCellDialog.resize(450, 200)
        EditShiftCellDialog.setAutoFillBackground(True)
        EditShiftCellDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(EditShiftCellDialog)
        QMetaObject.connectSlotsByName(EditShiftCellDialog)

        self.setupMainLayout(EditShiftCellDialog)
        self.setupDialogNav()
        self.setupFormArea()
        self.setupNavArea()

    def retranslateUi(self, EditShiftCellDialog):
        _translate = QCoreApplication.translate
        EditShiftCellDialog.setWindowTitle(_translate("EditShiftCellDialog", "班別編修"))
        EditShiftCellDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, EditShiftCellDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        EditShiftCellDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupFormArea(self):

        formArea = QWidget()
        formAreaLayout = QFormLayout()

        nameLabel = QLabel()
        nameLabel.setText("請輸入班別名稱：")
        nameLabel.setAlignment(Qt.AlignLeft)
        nameLabel.setFont(QFont("Noto Sans TC Regular", 10))
        nameLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.nameLineEdit = QLineEdit()
        self.nameLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.nameLineEdit.setAlignment(Qt.AlignCenter)
        self.nameLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.nameLineEdit.setStyleSheet(
            "QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")

        timeStartLabel = QLabel()
        timeStartLabel.setText("請指定起始時間：")
        timeStartLabel.setAlignment(Qt.AlignLeft)
        timeStartLabel.setFont(QFont("Noto Sans TC Regular", 10))
        timeStartLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.timeStart = QTimeEdit()
        self.timeStart.setFont(QFont("Noto Sans TC Regular", 10))
        self.timeStart.setAlignment(Qt.AlignCenter)
        self.timeStart.setCursor(QCursor(Qt.IBeamCursor))
        self.timeStart.setDisplayFormat("HH:mm:ss")
        self.timeStart.setStyleSheet(
            "QTimeEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QTimeEdit:selected{border-bottom:1px solid #f7931e;}")


        timeEndLabel = QLabel()
        timeEndLabel.setText("請指定結束時間：")
        timeEndLabel.setAlignment(Qt.AlignLeft)
        timeEndLabel.setFont(QFont("Noto Sans TC Regular", 10))
        timeEndLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.timeEnd = QTimeEdit()
        self.timeEnd.setFont(QFont("Noto Sans TC Regular", 10))
        self.timeEnd.setAlignment(Qt.AlignCenter)
        self.timeEnd.setDisplayFormat("HH:mm:ss")
        self.timeEnd.setCursor(QCursor(Qt.IBeamCursor))
        self.timeEnd.setStyleSheet(
            "QTimeEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QTimeEdit:selected{border-bottom:1px solid #f7931e;}")

        hourLabel = QLabel()
        hourLabel.setText("請指定工作時數：")
        hourLabel.setAlignment(Qt.AlignLeft)
        hourLabel.setFont(QFont("Noto Sans TC Regular", 10))
        hourLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.hourLineEdit = QLineEdit()
        self.hourLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.hourLineEdit.setAlignment(Qt.AlignCenter)
        self.hourLineEdit.setValidator(QDoubleValidator())
        self.hourLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.hourLineEdit.setStyleSheet(
            "QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")

        payHourLabel = QLabel()
        payHourLabel.setText("請指定給付時數：")
        payHourLabel.setAlignment(Qt.AlignLeft)
        payHourLabel.setFont(QFont("Noto Sans TC Regular", 10))
        payHourLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.payHourLineEdit = QLineEdit()
        self.payHourLineEdit.setFont(QFont("Noto Sans TC Regular", 10))
        self.payHourLineEdit.setAlignment(Qt.AlignCenter)
        self.payHourLineEdit.setValidator(QDoubleValidator())
        self.payHourLineEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.payHourLineEdit.setStyleSheet(
            "QLineEdit{border:0; background-color: white; border-bottom:1px solid #ddd} QLineEdit:focus{border-bottom:1px solid #f7931e;}")





        formAreaLayout.addRow(nameLabel, self.nameLineEdit)
        formAreaLayout.addRow(timeStartLabel, self.timeStart)
        formAreaLayout.addRow(timeEndLabel, self.timeEnd)
        formAreaLayout.addRow(hourLabel, self.hourLineEdit)
        formAreaLayout.addRow(payHourLabel, self.payHourLineEdit)
        formAreaLayout.setContentsMargins(30, 0, 30, 0)
        formArea.setLayout(formAreaLayout)

        self.mainLayout.addWidget(formArea, alignment=Qt.AlignVCenter)


    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()


        self.comfirm = QPushButton()
        self.comfirm.setText("送出")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)
