# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\EditTodayScheduleCellDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon


class Ui_EditTodayScheduleCellDialog(object):
    def setupUi(self, EditTodayScheduleCellDialog):
        EditTodayScheduleCellDialog.setObjectName("EditTodayScheduleCellDialog")
        EditTodayScheduleCellDialog.setWindowFlags(Qt.CustomizeWindowHint)
        EditTodayScheduleCellDialog.resize(450, 200)
        EditTodayScheduleCellDialog.setAutoFillBackground(True)
        EditTodayScheduleCellDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(EditTodayScheduleCellDialog)
        QMetaObject.connectSlotsByName(EditTodayScheduleCellDialog)

        self.setupMainLayout(EditTodayScheduleCellDialog)
        self.setupDialogNav()
        self.setupFormArea()
        self.setupNavArea()

    def retranslateUi(self, EditTodayScheduleCellDialog):
        _translate = QCoreApplication.translate
        EditTodayScheduleCellDialog.setWindowTitle(_translate("EditTodayScheduleCellDialog", "班表編修"))
        EditTodayScheduleCellDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, EditTodayScheduleCellDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        EditTodayScheduleCellDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupFormArea(self):

        formArea = QWidget()
        formAreaLayout = QFormLayout()

        shiftLabel = QLabel()
        shiftLabel.setText("請選擇班別：")
        shiftLabel.setAlignment(Qt.AlignLeft)
        shiftLabel.setFont(QFont("Noto Sans TC Regular", 10))
        shiftLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.shiftSelection = QComboBox()
        self.shiftSelection.setFont(QFont("Noto Sans TC Regular", 10))
        self.shiftSelection.setCursor(QCursor(Qt.PointingHandCursor))
        self.shiftSelection.setStyleSheet(
            "QComboBox{border: 0; background-color: white; border-bottom:1px solid #ddd;} QComboBox:selected{border-bottom: 1px solid #f7931e;} QComboBox::drop-down{border-style: none;}")

        roomLabel = QLabel()
        roomLabel.setText("請選擇實習室：")
        roomLabel.setAlignment(Qt.AlignLeft)
        roomLabel.setFont(QFont("Noto Sans TC Regular", 10))
        roomLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.roomSelection = QComboBox()
        self.roomSelection.setFont(QFont("Noto Sans TC Regular", 10))
        self.roomSelection.setCursor(QCursor(Qt.PointingHandCursor))
        self.roomSelection.setStyleSheet(
            "QComboBox{border: 0; background-color: white; border-bottom:1px solid #ddd;} QComboBox:selected{border-bottom: 1px solid #f7931e;} QComboBox::drop-down{border-style: none;}")

        staffLabel = QLabel()
        staffLabel.setText("請選擇工讀生：")
        staffLabel.setAlignment(Qt.AlignLeft)
        staffLabel.setFont(QFont("Noto Sans TC Regular", 10))
        staffLabel.setStyleSheet("QLabel{color: #f7931e;}")

        self.staffSelection = QComboBox()
        self.staffSelection.setFont(QFont("Noto Sans TC Regular", 10))
        self.staffSelection.setCursor(QCursor(Qt.PointingHandCursor))
        self.staffSelection.setStyleSheet(
            "QComboBox{border: 0; background-color: white; border-bottom:1px solid #ddd;} QComboBox:selected{border-bottom: 1px solid #f7931e;} QComboBox::drop-down{border-style: none;}")


        formAreaLayout.addRow(shiftLabel, self.shiftSelection)
        formAreaLayout.addRow(roomLabel, self.roomSelection)
        formAreaLayout.addRow(staffLabel, self.staffSelection)
        formAreaLayout.setContentsMargins(30, 0, 30, 0)
        formArea.setLayout(formAreaLayout)

        self.mainLayout.addWidget(formArea, alignment=Qt.AlignVCenter)


    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()


        self.comfirm = QPushButton()
        self.comfirm.setText("送出")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)

    def loadingShift(self, data: list):
        self.shiftSelection.clear()

        for item in data:
            self.shiftSelection.addItem(item[0], item[1])

    def loadingRoom(self, data: list):
        self.roomSelection.clear()

        for item in data:
            self.roomSelection.addItem(item[0], item[1])

    def loadingStaff(self, data: list):
        self.staffSelection.clear()

        for item in data:
            self.staffSelection.addItem(f'{item[0]} {item[1]}', item[2])
