# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\IntervalDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon



class Ui_IntervalDialog(object):
    def setupUi(self, IntervalDialog):
        IntervalDialog.setObjectName("IntervalDialog")
        IntervalDialog.resize(400, 150)
        IntervalDialog.setWindowFlags(Qt.CustomizeWindowHint)
        IntervalDialog.setAutoFillBackground(False)
        IntervalDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(IntervalDialog)
        QMetaObject.connectSlotsByName(IntervalDialog)

        self.setupMainLayout(IntervalDialog)
        self.setupDialogNav()
        self.setupFormArea()
        self.setupNavArea()

    def retranslateUi(self, IntervalDialog):
        _translate = QCoreApplication.translate
        IntervalDialog.setWindowTitle(_translate("IntervalDialog", "指定區間匯出"))
        IntervalDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))


    def setupMainLayout(self, IntervalDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0,0,0,0)
        IntervalDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addStretch()
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupFormArea(self):

        formArea = QWidget()
        formAreaLayout = QHBoxLayout()

        titleLabel = QLabel()
        titleLabel.setText("請指定匯出區間")
        titleLabel.setFont(QFont("Noto Sans TC Regular", 10))
        titleLabel.setAlignment(Qt.AlignLeft)

        self.interavalStart = QDateEdit()
        self.interavalStart.setFont(QFont("Noto Sans TC Regular", 10))
        self.interavalStart.setAlignment(Qt.AlignCenter)
        self.interavalStart.setCursor(QCursor(Qt.IBeamCursor))
        self.interavalStart.setDisplayFormat("yyyy-MM-dd")
        self.interavalStart.setStyleSheet("QDateEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QDateEdite:selected{border-bottom:1px solid #f7931e;}")

        self.interavalEnd = QDateEdit()
        self.interavalEnd.setFont(QFont("Noto Sans TC Regular", 10))
        self.interavalEnd.setAlignment(Qt.AlignCenter)
        self.interavalEnd.setCursor(QCursor(Qt.IBeamCursor))
        self.interavalEnd.setDisplayFormat("yyyy-MM-dd")
        self.interavalEnd.setStyleSheet("QDateEdit{border: 0; background-color: white; border-bottom: 1px solid #ddd} QDateEdite:selected{border-bottom:1px solid #f7931e;}")

        formAreaLayout.addWidget(titleLabel, 1)
        formAreaLayout.addWidget(self.interavalStart, 2)
        formAreaLayout.addWidget(self.interavalEnd, 2)
        formArea.setLayout(formAreaLayout)

        self.mainLayout.addWidget(formArea, alignment=Qt.AlignVCenter)


    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()


        self.comfirm = QPushButton()
        self.comfirm.setText("匯出")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)
