# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\MessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import close, logoIcon



class Ui_MessageDialog(object):
    def setupUi(self, MessageDialog):

        MessageDialog.setObjectName("MessageDialog")
        MessageDialog.resize(400, 150)
        MessageDialog.setWindowFlags(Qt.CustomizeWindowHint)
        MessageDialog.setAutoFillBackground(False)
        MessageDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(MessageDialog)
        QMetaObject.connectSlotsByName(MessageDialog)

        self.setupMainLayout(MessageDialog)
        self.setupDialogNav()
        self.setupContentArea()
        self.setupNavArea()

    def retranslateUi(self, MessageDialog):
        _translate = QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", ""))
        MessageDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512, 512))))

    def setupMainLayout(self, MessageDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        MessageDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavTitle = QLabel()
        self.dialogNavTitle.setFont(QFont("Noto Sans TC Regular", 10))
        self.dialogNavTitle.setAlignment(Qt.AlignLeft)

        self.dialogNavClose = QPushButton()
        self.dialogNavClose.setIcon(QIcon(SvgHelper.getQPixmapFromBytes(close, QSize(12, 12))))
        self.dialogNavClose.setIconSize(QSize(12, 12))
        self.dialogNavClose.resize(12, 12)
        self.dialogNavClose.setStyleSheet(
            "QPushButton{background-color: transparent; border-style:none; padding: 3px 3px 3px 3px;} QPushButton:hover{background-color: #eeeeee; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;} QPushButton:pressed{background-color: #999999; border-style:none; border-radius:5px; padding: 3px 3px 3px 3px;}")
        self.dialogNavClose.setCursor(QCursor(Qt.PointingHandCursor))

        dialogNavLayout.addWidget(self.dialogNavTitle)
        dialogNavLayout.addStretch(1)
        dialogNavLayout.addWidget(self.dialogNavClose)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav, alignment=Qt.AlignTop)

    def setupContentArea(self):
        self.messageLabel = QLabel()
        self.messageLabel.setFont(QFont("Noto Sans TC Regular", 10))
        self.messageLabel.setAlignment(Qt.AlignCenter)

        self.mainLayout.addWidget(self.messageLabel, alignment=Qt.AlignCenter)

    def setupNavArea(self):
        navArea = QWidget()
        navAreaLayout = QHBoxLayout()

        self.comfirm = QPushButton()
        self.comfirm.setText("確認")
        self.comfirm.setFont(QFont("Noto Sans TC Regular", 10))
        self.comfirm.setCursor(QCursor(Qt.PointingHandCursor))
        self.comfirm.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        self.cancel = QPushButton()
        self.cancel.setText("取消")
        self.cancel.setFont(QFont("Noto Sans TC Regular", 10))
        self.cancel.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton{color:#f7931e; border-style: none; border: 1px solid #f7931e; border-radius: 5px; padding: 5px 8px 5px 8px; background-color: white;} QPushButton:hover{color: white; background-color:#f7931e} QPushButton:pressed{color: white; background-color:#DC831A}")

        navAreaLayout.addStretch()
        navAreaLayout.addWidget(self.comfirm)
        navAreaLayout.addWidget(self.cancel)
        navArea.setLayout(navAreaLayout)

        self.mainLayout.addWidget(navArea, alignment=Qt.AlignBottom)

    def loadingTitle(self, MessageDialog, title: str):
        _translate = QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", title))
        self.dialogNavTitle.setText(title)

    def loadingMessage(self, message: str):
        self.messageLabel.setText(message)

