# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\桌面\TKUIofoCenterClient\uiFile\NoncancelanleMessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from utils.SvgHelper import SvgHelper

from icon.svg import logoIcon


class Ui_NoncancelanleMessageDialog(object):

    def setupUi(self, NoncancelanleMessageDialog):

        NoncancelanleMessageDialog.setObjectName("NoncancelanleMessageDialog")
        NoncancelanleMessageDialog.resize(400, 150)
        NoncancelanleMessageDialog.setWindowFlags(Qt.CustomizeWindowHint)
        NoncancelanleMessageDialog.setAutoFillBackground(False)
        NoncancelanleMessageDialog.setStyleSheet("QDialog{background-color:white;}")

        self.retranslateUi(NoncancelanleMessageDialog)
        QMetaObject.connectSlotsByName(NoncancelanleMessageDialog)

        self.setupMainLayout(NoncancelanleMessageDialog)
        self.setupDialogNav()
        self.setupContentArea()

    def retranslateUi(self, NoncancelanleMessageDialog):
        _translate = QCoreApplication.translate
        NoncancelanleMessageDialog.setWindowTitle(_translate("NoncancelanleMessageDialog", ""))
        NoncancelanleMessageDialog.setWindowIcon(QIcon(SvgHelper.getQPixmapFromBytes(logoIcon, QSize(512,512))))

    def setupMainLayout(self, NoncancelanleMessageDialog):
        self.mainLayout = QVBoxLayout()
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        NoncancelanleMessageDialog.setLayout(self.mainLayout)

    def setupDialogNav(self):
        dialogNav = QWidget()
        dialogNavLayout = QHBoxLayout()

        self.dialogNavTitle = QLabel()
        self.dialogNavTitle.setFont(QFont("Noto Sans TC Regular", 10))
        self.dialogNavTitle.setAlignment(Qt.AlignLeft)


        dialogNavLayout.addWidget(self.dialogNavTitle)

        dialogNav.setLayout(dialogNavLayout)

        self.mainLayout.addWidget(dialogNav)

    def setupContentArea(self):
        self.messageLabel = QLabel()
        self.messageLabel.setFont(QFont("Noto Sans TC Regular", 10))
        self.messageLabel.setAlignment(Qt.AlignCenter)

        self.mainLayout.addStretch(1)
        self.mainLayout.addWidget(self.messageLabel)
        self.mainLayout.addStretch(1)


    def loadingTitle(self, NoncancelanleMessageDialog, title: str):
        _translate = QCoreApplication.translate
        NoncancelanleMessageDialog.setWindowTitle(_translate("NoncancelanleMessageDialog", title))
        self.dialogNavTitle.setText(title)

    def loadingMessage(self, message: str):
        self.messageLabel.setText(message)

